version: "3"
services:
  database:
    image: "postgres:14-alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: map-matching
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
